# Generated by Django 5.0.6 on ...
from django.db import migrations

def populate_initial_activities(apps, schema_editor):
    ActivityCategory = apps.get_model('core', 'ActivityCategory')
    Activity = apps.get_model('core', 'Activity')

    # Kategorien erstellen
    cat_outdoor_sport, _ = ActivityCategory.objects.get_or_create(
        name='Outdoor Sport',
        description='Sportliche Aktivitäten an der frischen Luft.'
    )
    cat_indoor_sport, _ = ActivityCategory.objects.get_or_create(
        name='Indoor Sport',
        description='Sportliche Aktivitäten in geschlossenen Räumen.'
    )
    cat_kultur, _ = ActivityCategory.objects.get_or_create(
        name='Kultur & Bildung',
        description='Museen, Theater, Weiterbildung etc.'
    )
    cat_entspannung, _ = ActivityCategory.objects.get_or_create(
        name='Entspannung & Wellness',
        description='Aktivitäten zur Erholung von Körper und Geist.'
    )
    cat_kreativ, _ = ActivityCategory.objects.get_or_create(
        name='Kreativität & Handwerk',
        description='Malen, Basteln, Musik machen etc.'
    )
    cat_soziales, _ = ActivityCategory.objects.get_or_create(
        name='Soziales & Geselligkeit',
        description='Treffen mit Freunden, Spieleabende etc.'
    )

    # Aktivitäten erstellen
    Activity.objects.get_or_create(
        name='Joggen im Park',
        category=cat_outdoor_sport,
        description='Eine Runde Laufen im nahegelegenen Park.',
        is_outdoor=True,
        min_duration_minutes=30,
        max_duration_minutes=60,
        notes='Gute Laufschuhe empfohlen.'
    )
    Activity.objects.get_or_create(
        name='Fahrradtour',
        category=cat_outdoor_sport,
        description='Eine ausgedehnte Tour mit dem Fahrrad durch die Natur oder Stadt.',
        is_outdoor=True,
        min_duration_minutes=60,
        max_duration_minutes=240,
        notes='Helm nicht vergessen! Route vorher planen.'
    )
    Activity.objects.get_or_create(
        name='Museumsbesuch',
        category=cat_kultur,
        description='Besuch eines lokalen Kunst-, Geschichts- oder Technikmuseums.',
        is_outdoor=False,
        min_duration_minutes=90,
        max_duration_minutes=180,
        notes='Öffnungszeiten und Eintrittspreise prüfen.'
    )
    Activity.objects.get_or_create(
        name='Yoga zu Hause',
        category=cat_indoor_sport,
        description='Eine Yoga-Session mit Online-Video oder eigener Routine.',
        is_outdoor=False,
        min_duration_minutes=20,
        max_duration_minutes=60,
        notes='Bequeme Kleidung und eine Matte sind hilfreich.'
    )
    Activity.objects.get_or_create(
        name='Buch lesen',
        category=cat_entspannung,
        description='In einem guten Buch schmökern.',
        is_outdoor=False, # Kann auch Outdoor sein, aber als Default Indoor
        min_duration_minutes=30,
        max_duration_minutes=120,
        notes='Finde einen ruhigen Ort.'
    )
    Activity.objects.get_or_create(
        name='Meditieren',
        category=cat_entspannung,
        description='Kurze Meditation zur Stressreduktion und Fokusfindung.',
        is_outdoor=False,
        min_duration_minutes=10,
        max_duration_minutes=30,
    )
    Activity.objects.get_or_create(
        name='Malen oder Zeichnen',
        category=cat_kreativ,
        description='Kreativ werden mit Stift und Papier oder Pinsel und Leinwand.',
        is_outdoor=False,
        min_duration_minutes=45,
        max_duration_minutes=120,
    )
    Activity.objects.get_or_create(
        name='Spieleabend mit Freunden',
        category=cat_soziales,
        description='Brettspiele, Kartenspiele oder Videospiele zusammen spielen.',
        is_outdoor=False,
        min_duration_minutes=90,
        max_duration_minutes=240,
        notes='Snacks und Getränke bereitstellen!'
    )
    Activity.objects.get_or_create(
        name='Spaziergang in der Natur',
        category=cat_outdoor_sport, # Kann auch Entspannung sein
        description='Ein entspannter Spaziergang durch den Wald oder am See.',
        is_outdoor=True,
        min_duration_minutes=30,
        max_duration_minutes=90,
    )
    Activity.objects.get_or_create(
        name='Neues Rezept kochen/backen',
        category=cat_kreativ, # Kann auch Soziales sein, wenn man für andere kocht
        description='Ein unbekanntes Gericht oder einen Kuchen ausprobieren.',
        is_outdoor=False,
        min_duration_minutes=60,
        max_duration_minutes=180,
        notes='Zutaten vorher einkaufen.'
    )

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_friendship"), # Stelle sicher, dass die Abhängigkeit korrekt ist
    ]

    operations = [
        migrations.RunPython(populate_initial_activities),
    ]
